### ISSUE TITLE
Style using HERE vector tiles works in 1.61, but not 1.7 - white map

### ISSUE THREAD

**Issue by akac** [maputnik/editor#674] opened 2020-04-30 17:24 UTC
I'm still trying to figure out what broke - but our internal corporate style using HERE vector data works in 1.61, but just gives a white screen in 1.7.

Using the OpenLayer renderer sort of works (the terrain raster we have starts to work). Mapbox renderer only works in the 1.61, not 1.7.

I do see errors in the console.
[maputnik.github.io-1588267412962.log.zip](https://github.com/maputnik/editor/files/4560017/maputnik.github.io-1588267412962.log.zip)

**Comment by pathmapper** [comment] 2020-05-02 15:47
Hi @akac,

from your log files it looks like the main error message is 

> Uncaught TypeError: Cannot read property 'updateTransitions' of undefined

Maybe a starting point to investigate further: 
Since v1.6.1 we've introduced support of the [transition root property](https://docs.mapbox.com/mapbox-gl-js/style-spec/root/#transition) in https://github.com/maputnik/editor/pull/563.

You could remove layer by layer and root property by root property from your style file to find out what is causing the issue.

Any chance you could provide a style file to help us to replicate and diagnose the issue?

**Comment by akac** [comment] 2020-05-04 14:17
Try:
https://vltcdn-public.s3.amazonaws.com/mapping/production/v1/here_mapbox_day.json

**Comment by orangemug** [comment] 2020-05-04 14:49
@akac I haven't got time to fully verify right this minute, however changed the example here https://docs.mapbox.com/mapbox-gl-js/example/simple-map/ to use https://vltcdn-public.s3.amazonaws.com/mapping/production/v1/here_mapbox_day.json and the same issue occurred.

Seems like it's an issue with the latest version of mapbox-gl, I'll try to find the time to confirm later, if no one else beats me to it 😄

**Comment by pathmapper** [comment] 2020-05-04 16:16
The map is not rendered because there are Mapbox fonts and glyphs used in the style 
so there is a need for a Mapbox access token.


![grafik](https://user-images.githubusercontent.com/20856381/80987986-2432b280-8e33-11ea-9a5c-b30942e53a6a.png)

For some reason it's not working with the fallback token and also not working if a valid custom token is used in the style settings.

**Comment by pathmapper** [comment] 2020-05-04 16:39
Looks like the root cause is that the Mapbox sprite files are not accessible, they are failing with 404.

@akac could you please verify that they are still available in your Mapbox account?
If yes, could you please try the following URL with your Mapbox access token instead of [access token]?

https://api.mapbox.com/styles/v1/mapquest/ck60xw27l06cp1imp7k71780q/1nx90xzs9tttq9zi3kmdkudsl/sprite.json?access_token=[access token]

**Comment by akac** [comment] 2020-05-04 16:47
Yes, I believe the style is used in quite a few other places. I just tried the URL with my access token and its working fine as well.

**Comment by pathmapper** [comment] 2020-05-04 16:51
Could you please enter your Mapbox access token in the style settings in Maputnik `v1.7.0`:

I expect that the map would be rendered.

![grafik](https://user-images.githubusercontent.com/20856381/80991353-2ea37b00-8e38-11ea-9da3-f6f6e97c7084.png)

**Comment by akac** [comment] 2020-05-04 16:57
Yes - first place I looked. It was empty at first. So I entered it and it still was blank. Did a refresh. etc… Tried it on another machine.

**Comment by pathmapper** [comment] 2020-05-04 17:26
Could you provide a token for testing?

**Comment by akac** [comment] 2020-05-05 04:20
Any way I can send it to you privately?

**Comment by pathmapper** [comment] 2020-05-05 09:40
Yes, but I think it's better to have a public test case so others could also help debug this issue.

**Comment by pathmapper** [comment] 2020-05-05 10:01
Here is a test case using https://docs.mapbox.com/mapbox-gl-js/example/simple-map/ with your style and one of my tokens:

https://jsbin.com/dedamatagu/1/edit?html,output

There still failing requests, but a least there is a map rendered.

If the token is removed, then nothing is rendered:

https://jsbin.com/jodiqalifi/1/edit?html,output

**Comment by pathmapper** [comment] 2020-05-28 05:45
> https://vltcdn-public.s3.amazonaws.com/mapping/production/v1/here_mapbox_day.json

The style in question passes the validation with `gl-style-validate`.

If you open the style in Maputnik and switch to inspect mode, it crashes the editor:





![grafik](https://user-images.githubusercontent.com/20856381/83103269-acb11580-a0b6-11ea-80ec-9145221df4d0.png)

**Comment by akac** [comment] 2020-06-01 16:06
So is this a bug in the style or in the mapbox GL?

**Comment by pathmapper** [comment] 2020-06-05 13:40
@akac turns out this is a regression in Maputnik, which was introduced with f3b8c53.

https://github.com/maputnik/editor/pull/703 is a PR reverting this, you may try it in out with:
 https://codesandbox.io/embed/github/pathmapper/editor/tree/fix_674?view=preview

**Comment by orangemug** [comment] 2020-06-29 14:42
Closed by #703

**Closed by orangemug** 2020-06-29 14:42 UTC
Labels: bug
