### ISSUE TITLE
Can not increase line widths exponentially 

### ISSUE THREAD

**Issue by adamakhtar** [maputnik/editor#709] opened 2020-07-09 12:02 UTC
This is an awesome project. Thank you so much for creating it. Now I'm not sure if this is a bug or I'm simply misunderstanding how to use the feature but I'm trying to exponentially increase the width of various roads as the zoom increases but despite displaying the roads their widths will not increase at all. 

I'm using the maputnik cli tool v1.7.0 and editing a json file locally via

`./maputnik  --watch --file style.json`
 
## First attempt
I started to style my roads in Maputnik with a width of 1px across all zooms. They displayed fine. The next step was to make them exponentially increase in width. I had previously achieved this in the Mapbox studio editor so I thought I'd copy the "line-width" config from Mapbox over to my local Maputnik json config file. It looked like this:

```
"id" : ....
"type": ..
...
"paint": {
  "line-width": [
      "interpolate",
      ["exponential", 1.5],
      ["zoom"],
      6,
      0.3,
      10,
      0.75,
      14,
      2
  ]
  ...
}
```

However the Maputnik editor did not like this formatting. 

## Second attempt 

I deleted the width setting in the editor directly and tried to recreate it using the editor controls. There are more fields available in the Maputnik editor than in Mapbox and I was a little confused as to what I should be entering in each. However despite various combinations I could not get the width to exponentially increase. The road does show but only at a width of 1px. With the settings show below, I'd expect the road to be 5px at zoom 14 but it did not vary at all. 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/238342/87036227-71f9db80-c225-11ea-86a9-1a51d8806694.png">

Is this a bug or am I making a silly mistake?

**Comment by pathmapper** [comment] 2020-07-10 06:36
Hi @adamakhtar 

> However the Maputnik editor did not like this formatting.

I can't reproduce the issue, for me it works fine with the `v1.7.0` CLI:

<img src="https://user-images.githubusercontent.com/20856381/87122020-4fe37600-c284-11ea-90cc-03574564bc21.gif" width="250"/>

Maybe just a copy/paste error?

**Comment by pathmapper** [comment] 2020-07-10 09:23
@adamakhtar regarding your _Second attempt_:

The `base` input is currently missing and the UI is currently confusing, see #710, #711.

For the next release there will be an update with more descriptive fields, see https://github.com/maputnik/editor/pull/706.
You could try it out here https://codesandbox.io/s/infallible-browser-m49ws

Currently the best way to achieve what you want is using your expression
```

[
      "interpolate",
      ["exponential", 1.5],
      ["zoom"],
      6,
      0.3,
      10,
      0.75,
      14,
      2
]
```

as shown in https://github.com/maputnik/editor/issues/709#issuecomment-656510320 (using the _Convert to expression_ button) or editing directly the code in the JSON editor.

Does it work for you?

**Comment by adamakhtar** [comment] 2020-07-10 11:27
@pathmapper you are right. My attempt in step 1 was somehow faulty. Trying it again after a good nights sleep has done the trick. I'm not quite sure what I was doing wrong last night. My apologies for the non issue but I am very thankful for your quick reply. 

Re: the second attempt - yes converting it to an expression and editing it directly does work as you said. Thank you for also explaining the current problems with the UI and linking the relevant issues. I'm looking forward to seeing the fixes in the near future. 

Thanks again for all your help.

**Comment by pathmapper** [comment] 2020-07-10 12:49
Thanks for you feedback @adamakhtar, closing here.

**Closed by pathmapper** 2020-07-10 12:49 UTC
