### ISSUE TITLE
Weird behavior when adding a filter

### ISSUE THREAD

**Issue by doskabouter** [maputnik/editor#737] opened 2020-09-29 09:40 UTC
Maputnik version 1.7.0
Latest firefox on windows

When adding a filter, doubleclick to highlight "name" (the placeholder for new filters) and start typing $type.
Then the "Export style" dialog pops up, and when cancelled, the filter edit only shows the old style (plain json) with an error message "expected one of [Point, LineString, Polygon], "" found"

**Comment by pathmapper** [comment] 2020-09-29 20:40
Hi @doskabouter,

thanks for reporting, this is a duplicate of https://github.com/maputnik/editor/issues/712 which is already fixed by https://github.com/maputnik/editor/pull/729 and will be included in the [upcoming v1.8.0 release](https://github.com/maputnik/editor/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.8.0
).

**Closed by pathmapper** 2020-09-29 20:40 UTC
