### ISSUE TITLE
Exporting to PNG or other raster format.

### ISSUE THREAD

**Issue by Kwoalaka** [maputnik/editor#310] opened 2018-05-31 07:51 UTC
Hi,

Is there anyway to export this to a PNG or any other raster format?

I know i can create a printscreen, but i wanted to have a bigger resolution for a print.

Thanks in advance.

**Comment by orangemug** [comment] 2018-05-31 08:29
Hi @Kwoalaka and welcome to the Maputnik community. This has already been raised over in issue #180. Take a look at that issue and let us know if the suggested solution meets your requirements.

Also if you have time, please tell us what you use Maputnik for over in #164. Hearing stories helps to keep us motivated 😄

**Comment by Kwoalaka** [comment] 2018-05-31 11:18
Hi Roangemug,

I noticed, i was looking for a easy exporting method like mapbox offers.

Is there anyway i can use the json file with mapertive or something?

Sorry, i'm a complete noob with this

**Comment by orangemug** [comment] 2018-06-04 07:49
Hey @Kwoalaka so we are working on a raster export option, and we're getting closer to a working solution. We are however we're still some way off a working version, probably a few weeks.

For some clarification. Maputnik is an editor for the [mapbox-gl-js style spec](https://www.mapbox.com/mapbox-gl-js/style-spec/), 
you can export the JSON from the 'export modal' in the editor and use it anywhere you like. In issue #180 @pathmapper suggested some existing tools to export as a raster. [pkd2512 print maps](http://prasantakrdutta.com/print-maps) seems like the easiest way at the moment. If you're comfortable with node.js/npm here are the steps

 1. Create a new directory and place your exported style in that directory
 2. `cd` to that directory
 3. Install [http-server](https://www.npmjs.com/package/http-server) `npm i http-server` in that directory
 4. run `./node_modules/.bin/http-server --cors`
 5. Go to <http://prasantakrdutta.com/print-maps> add a custom style with the url <http://127.0.0.1:8081/PATH/TO/YOUR/STYLE.json>, using either a mapbox access token or a random string if you're not using mapbox data sources
 6. Your style will now appear in the select box on that page ready to export

**Comment by orangemug** [comment] 2018-06-09 12:51
Closing issue as duplicate of #180

**Closed by orangemug** 2018-06-09 12:51 UTC
