### ISSUE TITLE
Feature shows up twice in Inspect View

### ISSUE THREAD

**Issue by lukasmartinelli** [maputnik/editor#41] opened 2016-12-30 12:25 UTC
Because there is a style for all the data and an additional style to highlight the current layer
the popup shows the same feature twice.

![screenshot from 2016-12-30 13-24-32](https://cloud.githubusercontent.com/assets/1288339/21565054/67194ff4-ce93-11e6-9bfa-e69f95f10559.png)

**Comment by orangemug** [comment] 2017-03-07 15:28
I can't reproduce the issue... have you fixed this already?

**Comment by lukasmartinelli** [comment] 2017-03-07 16:03
> I can't reproduce the issue... have you fixed this already?

I don't remember haha. Could be that I explicitly filter out what is currently in inspect mode.
Inspect mode is quite a hack to be honest.

If it doesn't occur anymore we can close it.

**Comment by gregorywolanski** [comment] 2017-10-12 17:16
I tried to reproduce the issue. I guess I made it. 

If you could confirm it, I’ll be happy to dive into the codebase of Maputnik to try to fix the bug. :)

<img width="746" alt="screenshot" src="https://user-images.githubusercontent.com/787518/31509424-b73f0dbe-af81-11e7-8b21-987a020a2f90.png">

**Comment by orangemug** [comment] 2017-10-12 17:59
Hi @gregorywolanski thanks for a sample of the issue. So I think I know what's going on and I think it's kind of 'correct'. So I believe what is happening is that there are actually 2 overlapping features under the cursor in the source data. I added some logging in `src/components/map/FeatureLayerPopup.jsx` quickly and it looks like the `feature.id` is different in each case.

```
    // Just a snippet from src/components/map/FeatureLayerPopup.jsx
    const items = Object.keys(sources).map(vectorLayerId => {
      const layers = sources[vectorLayerId].map((feature, idx) => {
        console.log(">>>", vectorLayerId, feature.id);
```

I think the solution here is probably to also display the feature id in the inspect view. Note this will need doing in two places

 - map inspect view - clicking on the map in normal mode
 - inspect view - clicking on the inspect view in the toolbar

I'm open to other solutions also, let me know your thoughts.

**Comment by pathmapper** [comment] 2017-10-12 19:27
Hi, @orangemug do you suppose these are two different features? I am asking because it could be a feature "ovelapping itself" because of buffers if _feature.id_ is what is described here as _object ID-s_: https://github.com/openmaptiles/openmaptiles/issues/303

**Comment by orangemug** [comment] 2017-10-12 19:43
> ...do you suppose these are two different features?

@pathmapper I believe so but I'm not 100%, I only took a quick look. @gregorywolanski are you able to take a look and confirm?

**Comment by gregorywolanski** [comment] 2017-10-13 17:12
<img width="844" alt="screen shot 2017-10-13 at 19 11 14" src="https://user-images.githubusercontent.com/787518/31557760-6207cc90-b04a-11e7-9f4d-572226abbce1.png">

**Comment by lukasmartinelli** [comment] 2017-10-15 20:10
Yes I remember fixing it.

**Comment by gregorywolanski** [comment] 2017-10-15 20:16
How should I understand that? :)

**Comment by orangemug** [comment] 2017-10-15 21:34
> Yes I remember fixing it.

Yeah I'm a little confused as well with the comment @lukasmartinelli. I'm assuming there was an issue that was fixed. However as @gregorywolanski points out there is still an issue here. We appear to have 2 features with the same id underneath the cursor, as shown in the following

<img width="149" alt="with-same-id" src="https://user-images.githubusercontent.com/235915/31589384-7a184f30-b1f8-11e7-8656-3fef69aae339.png">

In addition to this it is possible to have 2 features with the same name and different ids under the cursor.

<img width="142" alt="with-diff-id" src="https://user-images.githubusercontent.com/235915/31589388-87922708-b1f8-11e7-8792-0e9eb3527f60.png">

So in my opinion there are 2 parts to the issue here

 1. A user can't tell 2 features with different ids apart from each other
 2. Why are we getting 2 features with the same id?

We can fix the first part of the issue by adding the feature id to the features in the inspector popup. As shown below.

<img width="163" alt="altered-diff-id" src="https://user-images.githubusercontent.com/235915/31589398-a5dc27f4-b1f8-11e7-8d9c-bd43607effcb.png">
<img width="189" alt="altered-same-id" src="https://user-images.githubusercontent.com/235915/31589399-a5fb686c-b1f8-11e7-9e2f-0d8dc66e7da9.png">

What's everyones thoughts on this???

As for the second part of the issue I have no idea why that's happening. It sounds like @pathmapper might have some insight though.

**Note:** All the above can be viewed with the 'OSM Liberty' style loaded at the following zoom level / position <https://maputnik.github.io/editor/#13.87/52.2130/21.0408>

**Comment by pathmapper** [comment] 2017-10-16 08:21
My thoughts on this:

1. The initial issue is fixed:

> Because there is a style for all the data and an additional style to highlight the current layer
> the popup shows the same feature twice.

This is what @lukasmartinelli remembered and it is also visible in inspect mode that this is not an issue anymore:

![image](https://user-images.githubusercontent.com/20856381/31599990-0a364fe8-b255-11e7-8259-650e50f6cd65.png)

![image](https://user-images.githubusercontent.com/20856381/31600010-18982e30-b255-11e7-9d46-e845df7eae2b.png)


<hr>

2. What we are seeing in the following screenshot is related to the buffer of the vector tiles: 

![image](https://user-images.githubusercontent.com/20856381/31600308-385422f0-b256-11e7-91ac-84848b5920aa.png)

If you are moving the mouse pointer a little bit up or down it looks like this:

![image](https://user-images.githubusercontent.com/20856381/31601214-6c6d43f2-b259-11e7-80b4-87b9b3ab419e.png)


"Inside" the buffer features are duplicated from adjacent tiles. 
So in inspect mode Maputnik is showing what is in the tiles. This is nothing wrong, the question is only if it is wanted to show it this way or to filter out duplicated features because of buffers (= don't show features in buffers)

More on buffers:

https://www.mapbox.com/vector-tiles/specification/#encoding-geom
https://www.mapbox.com/vector-tiles/specification/#clipping

See also:
https://github.com/mapbox/tippecanoe#controlling-clipping-to-tile-boundaries

<hr>


3. A feature which expands over several tiles may have a different ID for each tile, see this issue (same I linked before): https://github.com/openmaptiles/openmaptiles/issues/303

> It looks like the schema page does not specify how are are object ID-s set in the vector tiles. They seem to be sequential for every tile (1,2,3...), right? Now when there are several copies of same objects (e.g. POIs) due to buffers, then the same object in different tile will have different ID.

This is something which will be hopefully fixed in OpenMapTiles soon:
>  This could be easily achieved by copying a "natural" global UID, e.g. osm_id value from OSM database to object IDs

Looking at the feature ID could have several meanings at the moment:
IDs are the same -> same feature whithin 1 tile
IDs are the same -> different features of adjacent tiles, but having the same ID (by accident)
IDs are the same -> same feature exapanding over adjacent tiles, but having the same ID (by accident)

**Comment by gregorywolanski** [comment] 2017-10-22 08:59
@pathmapper 

2. Do you know any case in which duplicates could be useful?

**Comment by pathmapper** [comment] 2017-10-22 17:04
@gregorywolanski Only very rare cases for debugging like clipped labels at tile boundaries. I would prefer to remove the duplicates related to buffers in the inspect view of Maputnik if possible. Instead it would be useful to have an option to display the tile boundaries.

**Comment by gregorywolanski** [comment] 2017-10-27 17:50
OK, guys, how do you decide what to do with such issues in this project? :) Can I help in any way? :]

**Comment by orangemug** [comment] 2017-11-29 12:06
@gregorywolanski so I guess the first thing to work out is this possible

> I would prefer to remove the duplicates related to buffers in the inspect view of Maputnik if possible.

If so then lets do that.

If that's not possible then we could probably just show one feature in the popup and mark it in someway stating there are multiple to the user. How about `water (x3)` to show there are `3` duplicate layers for example. This means we're still telling the user the truth about the data source but not showing duplicate data to them.

With regards to

> ...it would be useful to have an option to display the tile boundaries 

Let open a new issue for that and work out where we'd put that option in the UI

Does that sound good @pathmapper ?

**Comment by pathmapper** [comment] 2017-11-29 12:49
@orangemug thanks, sounds good!

Just noticed that the mentioned issue [Use globally unique object ID-s](https://github.com/openmaptiles/openmaptiles/issues/303) has been added to the [v3.7 milestone of Openmaptiles](https://github.com/openmaptiles/openmaptiles/milestone/10), so maybe it will be part of the next release.

With unique object ID-s it should be possible to filter/remove the duplicates for OpenMapTiles, but maybe there is a way to remove the duplicates which would work for all vector tiles sources (if this issue exists also with other sources).

**Comment by gregorywolanski** [comment] 2017-12-03 19:14
> If that's not possible then we could probably just show one feature in the popup and mark it in someway stating there are multiple to the user. How about water (x3) to show there are 3 duplicate layers for example.

I think “water × 3” works better than “water (×3)”. It’s easier to read.

<img width="220" alt="1" src="https://user-images.githubusercontent.com/787518/33528765-3f022846-d866-11e7-8f79-fe1f62da079f.png">

Let me know what do you think, @orangemug and @pathmapper, and then I’ll create a pull request.

**Comment by orangemug** [comment] 2017-12-04 07:52
Looks good to me @gregorywolanski

**Comment by orangemug** [comment] 2018-01-30 21:46
Released in v1.1.0. Congrats @gregorywolanski it works great!

**Closed by orangemug** 2018-01-30 21:46 UTC
Labels: bug, help wanted

**Comment by gregorywolanski** [comment] 2018-01-31 17:50
@orangemug Can you please mail me at github.com@gregorywolanski.com?

**Comment by orangemug** [comment] 2018-01-31 17:55
@gregorywolanski message waiting in your inbox
