### ISSUE TITLE
Symbols: Default value for the “Image” property

### ISSUE THREAD

**Issue by gregorywolanski** [maputnik/editor#434] opened 2018-10-20 10:55 UTC
A user suggested that the „Image” property should get a default value (for example the first sprite) to give immediate feedback that the layer is working.

**Comment by orangemug** [comment] 2018-10-31 08:30
It's common to have a symbol layer without the `icon-image` set, text labels for example. Is there something I'm missing?

**Comment by pathmapper** [comment] 2018-10-31 12:55
> It's common to have a symbol layer without the icon-image set

Yes, [`icon-image`](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-icon-image) is optional.

I think what is requested here, is to show a default image if the value of `icon-image` is an empty string.

I'm afraid such a behaviour would be more confusing than it would help. 

To check if a symbol layer is working in general, it is possible to put some random text in the `text-field`.

There are also use cases where it is intended to have an empty string for `icon-image`, e.g. to be able to set layout properties which require `icon-image` and set the value of `icon-image` based on user interaction later in an application.

The cause for this survey feeback might be that there is currently no information available in the editor regarding which images are available in a sprite used by the style and the user therefore needs to know how to get this information elsewhere.

To show/list the available images in a sprite somewhere in the editor would be a nice feature.

**Comment by orangemug** [comment] 2018-10-31 18:01
@pathmapper so I guess there's nothing to do here, shall we close it.

**Comment by pathmapper** [comment] 2018-10-31 18:21
Yep.

**Closed by pathmapper** 2018-10-31 18:21 UTC
Labels: enhancement, mentioned in the 1st survey
