### ISSUE TITLE
How Can I Run This Into WIndows PC?

### ISSUE THREAD

**Issue by techmastersofficial** [maputnik/editor#339] opened 2018-07-11 06:03 UTC
How Can I Run This Into Windows PC?

**Comment by keum** [comment] 2018-07-16 22:59
hi @techmastersofficial , i'm assuming you would like to run Maputnik locally on your windows machine? if that is so, installing locally isn't too complicated but the issue is trying to run your own vector tile server. I'm using tileserver-gl. You can read try to follow this instruction that i did for local gis workshop back in May. https://pkgeo-org.github.io/vector%20tiles/2018/04/30/Maputnik.html

it explains various set up you have to do to run tileserver-gl locally. hope this helps.

**Comment by orangemug** [comment] 2018-07-27 13:08
It looks like @keum resolved this (thanks @keum)

@techmastersofficial I'm assuming this is resolved so I'll close the issue, just comment if it's not and we'll reopen.

**Closed by orangemug** 2018-07-27 13:08 UTC
