### ISSUE TITLE
JSON editor doesn't allow invalid intermediate states

### ISSUE THREAD

**Issue by sk1p** [maputnik/editor#484] opened 2019-01-06 16:49 UTC
Any time I try to change anything in the editor, it gets reset immediately if it results in invalid JSON (for example, adding a comma at the end to add a new element to an array). I guess this is kind of related to #353.

Actually, this is also true for other style inputs fields: try to clear our a mandatory(?) field via backspace (example: line width).  It always keeps the last digit, as an empty field would not be valid.

**Comment by pathmapper** [comment] 2019-01-29 12:56
Thanks for reporting @sk1p !

Also reported by @zstadler in https://github.com/maputnik/editor/issues/487:

> In the Docker version, some edits of the JSON code are not possible. For example, changing
> 
>     "line-dasharray": [
>       0.36,
>       0.18
>     ],
> to
> 
>     "line-dasharray": [
>       0.36,
>       0.18,
>       0.18,
>       0.18
>     ],
> is blocked as soon as the first "," key is pressed after "0.18".

This seems to be a regression since `v1.5.0` and we should fix it for the next release.

>  I guess this is kind of related to #353.

Yep, I think so too. Maybe this one is also related: https://github.com/maputnik/editor/issues/488.

**Comment by pathmapper** [comment] 2019-03-06 07:14
According to `git bisect` this was introduced with https://github.com/maputnik/editor/commit/1a8349f82158cda50d0791e537b8f438d769f171.

**Comment by pathmapper** [comment] 2019-03-06 14:04
The bug is related to the switch from `componentWillReceiveProps` -> `getDerivedStateFromProps` (`JSONEditor.jsx` in https://github.com/maputnik/editor/commit/1aa90bef3738e1bdbc8189af91337d9d02085b46#diff-a85193e1bed4f1ffc51b04784dee3711).

Reverting to 

```
UNSAFE_componentWillReceiveProps(nextProps) {
    this.setState({
      code: JSON.stringify(nextProps.layer, null, 2)
    })
```

allows invalid intermediate states again.

**Comment by petrsloup** [comment] 2019-03-06 15:05
The same is happening in the numerical inputs (e.g. opacity) -- it's not possible to change the values (If I write "0.", it get's "reverted" to "0" before I get a chance to finish inputting the correct value.)

**Comment by pathmapper** [comment] 2019-03-06 17:13
@petrsloup thanks, sounds similar but a bit different than https://github.com/maputnik/editor/issues/488.

Can't reproduce, do you see this with a public OpenMapTiles style? If yes, which style and which layer?

**Comment by petrsloup** [comment] 2019-03-07 07:12
Yes, this happens with any style (I think it's the identical issue as this one -- the `getDerivedStateFromProps` is the issue somehow.)

**Comment by pathmapper** [comment] 2019-03-07 14:16
Submitted a potential fix in https://github.com/maputnik/editor/pull/501 .

@petrsloup @sk1p @zstadler maybe you would like to try it out, your feedback would be much appreciated:
https://1281-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Please note: This is only for fixing the JSON editor.

**Comment by zstadler** [comment] 2019-03-07 17:18
Thanks @pathmapper for the potential fix!

When I try to enter `-0.4` as a numeric value, after typing `-0`, the cursor jumps to the end of the JSON code and the `.4` suffix appears after the closing bracket of the code:

![image](https://user-images.githubusercontent.com/1304610/53975192-f5289000-410c-11e9-8adf-363e9386565b.png)

Perhaps this is a result of trying to enter semantically-incorrect data in the `stops` array. However, it is strange for the cursor to jump as a result of such an error.

**Comment by sk1p** [comment] 2019-03-07 17:29
@pathmapper Thanks! Seems to work from a short check. @zstadler I can confirm the issue with `-0`. Strangely, `-1.something` works fine. In my tests, even typing `-0` outside of the context of `stops` triggers this behavior, for example as the value for any other key.

**Comment by pathmapper** [comment] 2019-03-10 08:47
@zstadler @sk1p thanks for your feedback! The bug _cursor jumps to the end of the JSON code_  exists since `v1.1.0`, opened https://github.com/maputnik/editor/issues/502 to track it.

The _numerical input_ bug is tracked in https://github.com/maputnik/editor/issues/488.

**Closed** 2019-04-16 05:05 UTC
Labels: bug
